[2024-05-18 00:43:42,505] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: stock_historic_prices.fill-stock_history 2024-05-18T00:43:38.229239+00:00 [queued]>
[2024-05-18 00:43:42,616] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: stock_historic_prices.fill-stock_history 2024-05-18T00:43:38.229239+00:00 [queued]>
[2024-05-18 00:43:42,620] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2024-05-18 00:43:42,623] {taskinstance.py:1018} INFO - Starting attempt 1 of 2
[2024-05-18 00:43:42,630] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2024-05-18 00:43:42,664] {taskinstance.py:1038} INFO - Executing <Task(PythonOperator): fill-stock_history> on 2024-05-18T00:43:38.229239+00:00
[2024-05-18 00:43:42,693] {standard_task_runner.py:51} INFO - Started process 4484 to run task
[2024-05-18 00:43:42,707] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'stock_historic_prices', 'fill-stock_history', '2024-05-18T00:43:38.229239+00:00', '--job-id', '5', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/stock_historic_prices.py', '--cfg-path', '/tmp/tmpsdw8vbxa']
[2024-05-18 00:43:42,723] {standard_task_runner.py:76} INFO - Job 5: Subtask fill-stock_history
[2024-05-18 00:43:42,986] {logging_mixin.py:103} INFO - Running <TaskInstance: stock_historic_prices.fill-stock_history 2024-05-18T00:43:38.229239+00:00 [running]> on host 6ce3e0b0dd10
[2024-05-18 00:43:43,148] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=stock_historic_prices
AIRFLOW_CTX_TASK_ID=fill-stock_history
AIRFLOW_CTX_EXECUTION_DATE=2024-05-18T00:43:38.229239+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-18T00:43:38.229239+00:00
[2024-05-18 00:43:43,166] {logging_mixin.py:103} INFO - Conexión exitosa a PostgreSQL
[2024-05-18 00:43:58,002] {local_task_job.py:170} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-05-18 00:43:58,012] {process_utils.py:95} INFO - Sending Signals.SIGTERM to GPID 4484
[2024-05-18 00:43:58,014] {taskinstance.py:1214} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-05-18 00:43:58,115] {logging_mixin.py:103} INFO - Error al ejecutar la consulta de insert: Task received SIGTERM signal
[2024-05-18 00:43:58,166] {logging_mixin.py:103} INFO - Desconexión exitosa de PostgreSQL
[2024-05-18 00:43:58,536] {python.py:118} INFO - Done. Returned value was: None
[2024-05-18 00:43:58,575] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=stock_historic_prices, task_id=fill-stock_history, execution_date=20240518T004338, start_date=20240518T004342, end_date=20240518T004358
[2024-05-18 00:43:58,658] {taskinstance.py:1195} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-18 00:43:58,720] {process_utils.py:61} INFO - Process psutil.Process(pid=4484, status='terminated', exitcode=0, started='00:43:42') (4484) terminated with exit code 0
[2024-05-18 00:43:58,727] {local_task_job.py:118} INFO - Task exited with return code 0
