[2024-05-18 00:20:23,820] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: stock_historic_prices.fill-stock_history 2024-05-17T00:00:00+00:00 [queued]>
[2024-05-18 00:20:23,838] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: stock_historic_prices.fill-stock_history 2024-05-17T00:00:00+00:00 [queued]>
[2024-05-18 00:20:23,839] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2024-05-18 00:20:23,841] {taskinstance.py:1018} INFO - Starting attempt 1 of 2
[2024-05-18 00:20:23,842] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2024-05-18 00:20:23,880] {taskinstance.py:1038} INFO - Executing <Task(PythonOperator): fill-stock_history> on 2024-05-17T00:00:00+00:00
[2024-05-18 00:20:23,889] {standard_task_runner.py:51} INFO - Started process 764 to run task
[2024-05-18 00:20:23,899] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'stock_historic_prices', 'fill-stock_history', '2024-05-17T00:00:00+00:00', '--job-id', '6', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/stock_historic_prices.py', '--cfg-path', '/tmp/tmp79ukw4ig']
[2024-05-18 00:20:23,906] {standard_task_runner.py:76} INFO - Job 6: Subtask fill-stock_history
[2024-05-18 00:20:24,003] {logging_mixin.py:103} INFO - Running <TaskInstance: stock_historic_prices.fill-stock_history 2024-05-17T00:00:00+00:00 [running]> on host 4367f4ce7644
[2024-05-18 00:20:24,119] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=stock_historic_prices
AIRFLOW_CTX_TASK_ID=fill-stock_history
AIRFLOW_CTX_EXECUTION_DATE=2024-05-17T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-17T00:00:00+00:00
[2024-05-18 00:20:24,135] {logging_mixin.py:103} INFO - Conexi贸n exitosa a PostgreSQL
[2024-05-18 00:21:54,565] {logging_mixin.py:103} INFO - Error al ejecutar la consulta de insert: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
[2024-05-18 00:21:54,586] {logging_mixin.py:103} INFO - 
[2024-05-18 00:21:55,350] {logging_mixin.py:103} INFO - Desconexi贸n exitosa de PostgreSQL
[2024-05-18 00:21:56,413] {python.py:118} INFO - Done. Returned value was: None
[2024-05-18 00:21:56,585] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=stock_historic_prices, task_id=fill-stock_history, execution_date=20240517T000000, start_date=20240518T002023, end_date=20240518T002156
[2024-05-18 00:21:56,653] {taskinstance.py:1195} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-18 00:21:56,727] {local_task_job.py:118} INFO - Task exited with return code 0
[2024-05-18 00:43:40,500] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: stock_historic_prices.fill-stock_history 2024-05-17T00:00:00+00:00 [queued]>
[2024-05-18 00:43:40,523] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: stock_historic_prices.fill-stock_history 2024-05-17T00:00:00+00:00 [queued]>
[2024-05-18 00:43:40,525] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2024-05-18 00:43:40,527] {taskinstance.py:1018} INFO - Starting attempt 1 of 2
[2024-05-18 00:43:40,529] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2024-05-18 00:43:40,558] {taskinstance.py:1038} INFO - Executing <Task(PythonOperator): fill-stock_history> on 2024-05-17T00:00:00+00:00
[2024-05-18 00:43:40,567] {standard_task_runner.py:51} INFO - Started process 4475 to run task
[2024-05-18 00:43:40,577] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'stock_historic_prices', 'fill-stock_history', '2024-05-17T00:00:00+00:00', '--job-id', '4', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/stock_historic_prices.py', '--cfg-path', '/tmp/tmpu3dg5ygw']
[2024-05-18 00:43:40,588] {standard_task_runner.py:76} INFO - Job 4: Subtask fill-stock_history
[2024-05-18 00:43:40,725] {logging_mixin.py:103} INFO - Running <TaskInstance: stock_historic_prices.fill-stock_history 2024-05-17T00:00:00+00:00 [running]> on host 6ce3e0b0dd10
[2024-05-18 00:43:40,876] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=stock_historic_prices
AIRFLOW_CTX_TASK_ID=fill-stock_history
AIRFLOW_CTX_EXECUTION_DATE=2024-05-17T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-17T00:00:00+00:00
[2024-05-18 00:43:40,889] {logging_mixin.py:103} INFO - Conexi贸n exitosa a PostgreSQL
[2024-05-18 00:43:50,815] {local_task_job.py:170} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-05-18 00:43:50,827] {process_utils.py:95} INFO - Sending Signals.SIGTERM to GPID 4475
[2024-05-18 00:43:50,834] {taskinstance.py:1214} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-05-18 00:43:50,874] {logging_mixin.py:103} INFO - Error al ejecutar la consulta de insert: Task received SIGTERM signal
[2024-05-18 00:43:50,936] {logging_mixin.py:103} INFO - Desconexi贸n exitosa de PostgreSQL
[2024-05-18 00:43:51,117] {python.py:118} INFO - Done. Returned value was: None
[2024-05-18 00:43:51,138] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=stock_historic_prices, task_id=fill-stock_history, execution_date=20240517T000000, start_date=20240518T004340, end_date=20240518T004351
[2024-05-18 00:43:51,188] {taskinstance.py:1195} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-18 00:43:51,222] {process_utils.py:61} INFO - Process psutil.Process(pid=4475, status='terminated', exitcode=0, started='00:43:40') (4475) terminated with exit code 0
[2024-05-18 00:43:51,227] {local_task_job.py:118} INFO - Task exited with return code 0
